apiVersion: v1
kind: Service
metadata:
  name: whatfix-enduser-api-service
  namespace: git
spec:
  selector:
    app: whatfix-enduser-api-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
  - 13.126.22.32
